server:
  port: 8761

eureka:
  instance:
    hostname: server_default
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://127.0.0.1:8762/eureka/,http://127.0.0.1:8763/eureka/